---
layout: project
title: Holographic SAR for airport imaging applications
description: Co-wrote the proposal for a novel scene imaging system to help avoid collisions in aircraft maintenance operations.
client: RampAware (EU FP7)
client_brandmark: eu_fp7.jpg
patent: No
image: holographic_sar.png
domains: Electronics
url: http://cordis.europa.eu/project/rcn/107426_en.html
start: December 2012
end: December 2012
contribution: Writing
status: Concept
trl: 3
stage: Application
arena: Corporate
tags: Electronics,Writing,Concept,TRL3,Application,Corporate
---