---
layout: project
title: Project Sphere - Socio-environmental design research
description: Project Sphere focused on Bangalore-centric approaches to solve challenges around the resource areas of air, energy, food, waste and water.
client: Jaaga
client_brandmark: jaaga.png
patent: No
image: sphere.jpg
domains: Air, Energy, Food, Waste, Water
url: http://projectsphere.jaagastartup.in
start: July 2015
end: September 2015
contribution: Design, Writing
status: Released
stage: Market
arena: Startup
tags: Air, Energy, Food, Waste, Water,Design, Writing,Released,TRL,Market,Startup
---